import '../styles/globals.css'
import Head from "next/head";

export const metadata = {
    title: 'Marketplace - choose your best course',
    description: 'Marketplace. Generated by create next app',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
    return (
        <html lang="ru">
        <Head>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
                    <link
                        href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@300;400;500;600;700&display=swap"
                        rel="stylesheet"/>

        </Head>
        <body>{children}</body>
        </html>
)
}
